##### this is the guide to rCGH package. use this with the pdf in docs


## set working directory
working_dir = "C:/Users/e.bordron/Desktop/CGH-scoring/M2_internship_Bergonie/scripts/working_dir"
setwd(working_dir)
## open working directory in Files tab
rstudioapi::filesPaneNavigate(working_dir)
#loading libraries
library(rCGH)

## define paths
sampleName = "5-LD"
# sampleName = "6-VJ"
# sampleName = "7-DG"
pathToTxt = paste0("C:/Users/e.bordron/Desktop/CGH-scoring/data/working_data/from_laetitia/all_probeset/",sampleName,".probeset.txt")
outputFolder = paste0("C:/Users/e.bordron/Desktop/CGH-scoring/M2_internship_Bergonie/results/rCGH/",sampleName)
outputFolder_plots = file.path(outputFolder, "plots")


## ----style-knitr, eval=TRUE, echo=FALSE, results="asis"--------------------
BiocStyle::latex()

## ----setup, include=FALSE-----------------------------------------------------
options(width = 80)
require(knitr)
opts_chunk$set(dev='png', prompt=TRUE, comment=NA, tidy=FALSE)

## ----readFiles, warning=FALSE, message=FALSE----------------------------------
filePath = 
# filePath <- system.file("extdata", "Affy_cytoScan.cyhd.CN5.CNCHP.txt.bz2", package = "rCGH")
# cgh <- readAffyCytoScan(filePath, sampleName = "CSc-Example",
#                         labName = "myLab")
filePath <- system.file("extdata", "oncoscan.tsv.bz2", package = "rCGH") # template file generated by APT program to produce copy number.
customFilePath = pathToTxt
cgh = rCGH::readAffyOncoScan(customFilePath)

## ----cgh, warning=FALSE, message=FALSE----------------------------------------
cgh

## ----addInfo------------------------------------------------------------------
setInfo(cgh, "item1") <- 35
setInfo(cgh, "item2") <- TRUE
setInfo(cgh, "item3") <- "someComment"

## ----getInfo------------------------------------------------------------------
getInfo(cgh)
getInfo(cgh, c("item1", "item3"))

## ----adjustSignal-------------------------------------------------------------
cgh <- adjustSignal(cgh, nCores=1)

## ----SegmentCGH---------------------------------------------------------------
cgh <- segmentCGH(cgh, nCores=1)
segTable <- getSegTable(cgh)

## ----segTable-----------------------------------------------------------------
head(segTable)

## ----EMnormalize--------------------------------------------------------------
cgh <- EMnormalize(cgh)

## ----plotDensity, fig.width=7, fig.height=5, fig.show='hide'------------------
plotDensity(cgh)

## ----byGeneTable--------------------------------------------------------------
geneTable <- byGeneTable(segTable)
head(geneTable, n=3)

## ----byGeneTable2-------------------------------------------------------------
byGeneTable(segTable, "erbb2", genome = "hg19")[,1:6]
byGeneTable(segTable, "erbb2", genome = "hg18")[,1:6]

## ----getParams----------------------------------------------------------------
getParam(cgh)[1:3]

## ----getProfile, fig.width=7.7, fig.height=9.5, fig.show='hide'---------------
multiplot(cgh, symbol = c("egfr", "erbb2"))

## ----recenter, fig.width=7.5, fig.height=4, fig.show='hide'-------------------
# Recentering on peak #2
recenter(cgh) <- 2
plotProfile(cgh, symbol = c("egfr", "erbb2"))

## ----view, eval=FALSE, echo=TRUE----------------------------------------------
#  view(cgh)

## ----exampleFiles-------------------------------------------------------------
list.files(system.file("extdata", package = "rCGH"))

## ----session------------------------------------------------------------------
sessionInfo()
